namespace: testing 
name: k8s_demo_collection
version: 0.0.3
authors:
  - 'Chris Houseknecht house@redhat.com'

description: This is a test collection that contains the Ansible K8s modules. 

license:
  - GPL-3.0-or-later

tags:
  - k8s 
  - kubernetes 
readme: README.md
dependencies:
repository: https://github.com/chouseknecht/collection.git
documentation: https://github.com/chouseknecht/collection/blob/master/README.md
homepage: https://github.com/chouseknecht/collection
issues: https://github.com/chouseknecht/collection/issues
